version = 0.1
[default.deploy.parameters]
stack_name = "smithy-lambda-url-example"
resolve_s3 = true
s3_prefix = "smithy-lambda-url-example"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
