AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  example of a lambda url function and smithy model

Resources:

  Site:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./lambda-handler
      Timeout: 3
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [ arm64 ]
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
  SiteLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Site}"
      RetentionInDays: 14

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt SiteUrl.FunctionUrl
